version: '3.8'

networks:
  dev:
    name: valentine-network
    driver: bridge

services:
  db:
    image: 'postgres:latest'
    container_name: valentine-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - dev
    logging:
      driver: 'json-file'
      options:
        max-size: '20m'
        max-file: '5'
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=200'
      - '-c'
      - 'shared_buffers=256MB'
      - '-c'
      - 'effective_cache_size=768MB'
      - '-c'
      - 'work_mem=16MB'
      - '-c'
      - 'synchronous_commit=off'
      - '-c'
      - 'checkpoint_timeout=1h'
      - '-c'
      - 'max_wal_size=1GB'

  api:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    container_name: valentine-server
    restart: unless-stopped
    ports:
      - '${BACKEND_PORT}:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - COOKIE_SECRET=${COOKIE_SECRET}
      - WEBSITE_BASE_URL=${WEBSITE_BASE_URL}
    networks:
      - dev
    logging:
      driver: 'json-file'
      options:
        max-size: '20m'
        max-file: '5'

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    container_name: valentine-client
    restart: unless-stopped
    ports:
      - '${FRONTEND_PORT}:3000'
    depends_on:
      - api
    environment:
      - WEBSITE_BASE_URL=${WEBSITE_BASE_URL}
    networks:
      - dev
    logging:
      driver: 'json-file'
      options:
        max-size: '20m'
        max-file: '5'

volumes:
  postgres:
    name: valentine-postgres-data12
    driver: local
